repeats: [0, 1]
duration: 30  
services: 
  - Booking

interference_config:
  cpu:
    cpu_size: 0.25
    mem_size: 10Mi
    pod_range: [0]
  mem:
    cpu_size: 0.01
    mem_size: 10Mi
    pod_range: [0]

workload_config:
  wrk_path: python  # wrk 대신 python 사용
  services:
    Booking:
      max_clients: 1
      thread_num: 0         # Python 워크로드엔 의미 없음 (필요 시 삭제 가능)
      connection_num: 0     # ↑ same
      throughput: 5         # QPS per client
      script_path: workloadGenerator/trainticketWorkload.py  # Python 경로로 변경
      url: http://10.0.1.106:32677             # ts-login-service 주소

collector_config:
  jaeger_host: http://10.0.1.106:30095
  entry_point: ts-login-service
  max_traces: 100000
  monitor_interval: 1
