data_path: data_train
figure_path: data_train/figures
yaml_repo_path: yamlRepository/trainTicket
namespace: train-ticket
app_img: swlove2024
nodes_for_test:
- node6
- node7

# prometheus_host: http://192.168.199.233:30090  # Prometheus 없이 트레이스만 수집
prometheus_host: null
nodes_for_infra:
- masternode
- node6
- node7
pod_spec:
  cpu_size: 0.2
  mem_size: 512Mi

replicas:
  Booking:
    ts-ui-dashboard: 1
    ts-user-service: 1
    ts-travel-service: 1
    ts-route-service: 1
    ts-station-service: 1
    ts-train-service: 1
    ts-price-service: 1
    ts-assurance-service: 1
    ts-food-service: 1
    ts-contact-service: 1
    ts-preserve-service: 1
    ts-order-service: 1
    ts-seat-service: 1
    ts-payment-service: 1
    ts-notification-service: 1