server:
  port: 12347

spring:
  application:
    name: ts-contacts-service
  cloud:
    config:
      uri: http://ts-config-service:15679
  data:
    mongodb:
      host: ts-contacts-mongo
      database: ts
      port: 27017

