data_path: data_hotel
figure_path: data_hotel/figures
yaml_repo_path: yamlRepository/hotelReservation
namespace: hotel-reserv
app_img: nicklin9907/erms:hotelreservation-1.0
nodes_for_test:
- masternode
- node6
- node7

prometheus_host: http://192.168.49.2:30090
nodes_for_infra:
- masternode
- node6
- node7
pod_spec:
  cpu_size: 0.1
  mem_size: 200Mi

replicas:
  Search:
    frontend: 8
    geo: 2
    profile: 5
    rate: 2
    recommendation: 2
    reservation: 5
    search: 2
    
  Recommendation:
    frontend: 8
    geo: 2
    profile: 5
    rate: 2
    recommendation: 2
    reservation: 5
    search: 2