# HTTP Server
server:
  port: 12344  # HTTP (Tomcat) port

spring:
  application:
    name: ts-register-service
  data:
    mongodb:
      host: ts-account-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017

opentracing:
  jaeger:
    udp-sender:
      host: jaeger
      port: 6831